[env:blackpill_f411ce]
platform          = ststm32
board             = blackpill_f411ce
framework         = cmsis
board_build.mcu   = stm32f411ceu6
board_build.f_cpu = 96000000L
upload_protocol   = serial
upload_port       = COM7
upload_speed      = 115200

monitor_port      = COM7
monitor_speed     = 115200
